### PR TITLE
Update MF7 recipe to latest changes in ENDF-102

### PR DESCRIPTION
**Pull request by marquezj**
Moved the PR to `dev` as requested in #3.

### CODE REVIEW

**Comment by gschnabel** [comment]
@marquezj Before I finally push the change to the dev branch, I would like to test the ENDF recipe extension on a file that uses the mixed coherent/incoherent representation and general information in MF7/MT451. Do you have an ENDF file handy that employs these options? I guess you can attach an ENDF file here to a new comment, but any other way of making it available to me is equally fine.

**Comment by marquezj** [comment]
Oh, sorry. I just realized I made the PR from dev to your main.

Regarding the mixed elastic format, yes, we have many of them here:

https://github.com/highness-eu/NJOY-NCrystal-Library/tree/master/mixed_elastic

For instance, the mixed elastic evaluation for metallic aluminum:

https://github.com/highness-eu/NJOY-NCrystal-Library/blob/master/mixed_elastic/Al-006/tsl-Al_sg225_Aluminum-iel100.endf.tar.xz

The MF7/MT451 I do not have files in a repo yet, and I do not think there are files with this feature in open repositories (I have only seen them in the ENDF/B-VIII.1beta repository). But I can create a simple evaluation for test purposes.

I will reply to this thread when I have the file.

**Comment by marquezj** [comment]
@gschnabel please find attached an example TSL file with the new sections, the NJOY processing script and the plots from the ACE file.

[Al.zip](https://github.com/IAEA-NDS/endf-parserpy/files/15465713/Al.zip)
[Al-006-00.pdf](https://github.com/IAEA-NDS/endf-parserpy/files/15465714/Al-006-00.pdf)

**Comment by gschnabel** [comment]
All the suggested changes have been incorporated and TSL Al file added to to the testdata.

**Pull request closed without merging**
